services:
  api:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
